-- 0. 암호화 확장기능 활성화
create extension if not exists pgcrypto;

-- 1. 기존 데이터 초기화 (확실하게 삭제)
drop table if exists public.galleries cascade;
drop table if exists public.popups cascade;
drop table if exists public.inquiries cascade;
drop table if exists public.profiles cascade;

-- 2. profiles 테이블 생성
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  login_id text unique not null,
  email text unique not null,
  full_name text,
  birth_date date,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 통합 테이블 생성 (팝업, 상담, 갤러리)
create table public.popups (
  id bigint generated by default as identity primary key,
  title text not null, image_url text not null, link_url text, is_active boolean default true, created_at timestamp with time zone default now()
);
create table public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null, phone text not null, 
  treatment text, -- 얼굴/바디 컨투어링, 스킨부스터, 리프팅, 미백/모공/흉터, 줄기세포 (상세 명칭 포함 가능)
  content text, status text default 'pending', created_at timestamp with time zone default now(),
  preferred_date text
);
create table public.galleries (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('얼굴/바디 컨투어링', '스킨부스터', '리프팅', '미백/모공/흉터', '줄기세포')), 
  treatment text not null, description text, 
  before_image_url text not null, after_image_url text not null, created_at timestamp with time zone default now()
);

-- 4. 보안 설정 (RLS 활성화)
alter table public.profiles enable row level security;
alter table public.popups enable row level security;
alter table public.inquiries enable row level security;
alter table public.galleries enable row level security;

-- 5. 권한 정책 설정 (기존 정책 삭제 후 재생성하여 에러 방지)
-- Profiles
drop policy if exists "Public view profiles" on public.profiles;
drop policy if exists "Individual insert/update profiles" on public.profiles;
create policy "Public view profiles" on public.profiles for select using (true);
create policy "Individual insert/update profiles" on public.profiles for all using (auth.uid() = id);

-- Popups
drop policy if exists "Public view popups" on public.popups;
drop policy if exists "Admin manage popups" on public.popups;
create policy "Public view popups" on public.popups for select using (is_active = true);
create policy "Admin manage popups" on public.popups for all using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- Inquiries
drop policy if exists "Public insert inquiries" on public.inquiries;
drop policy if exists "Admin manage inquiries" on public.inquiries;
create policy "Public insert inquiries" on public.inquiries for insert with check (true);
create policy "Admin manage inquiries" on public.inquiries for all using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- Galleries
drop policy if exists "Public view galleries" on public.galleries;
drop policy if exists "Admin manage galleries" on public.galleries;
create policy "Public view galleries" on public.galleries for select using (true);
create policy "Admin manage galleries" on public.galleries for all using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- 6. 관리자 계정 생성 (기존 사용자가 없을 경우만 실행)
-- 주의: auth.users 직접 삽입은 Supabase 권장 사항은 아니지만, 초기 설정 용도로 사용 가능
-- 실제 운영 환경에서는 Supabase Dashboard를 통한 생성을 권장합니다.

-- 7. 이미지 저장소(Storage) 권한 설정 (중복 에러 방지 포함)
-- storage.objects 에 대한 정책은 storage 스키마에 권한이 있어야 함
-- create policy "Anyone can view images" on storage.objects for select using (bucket_id = 'admin-images');
-- create policy "Admin can manage images" on storage.objects for all using (
--   bucket_id = 'admin-images' and 
--   exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
-- );

-- 8. 회원탈퇴용 DB 함수 (auth.users 삭제 → profiles cascade 자동 삭제)
create or replace function delete_user()
returns void
language plpgsql
security definer
as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;

-- 9. 캐시 갱신
NOTIFY pgrst, 'reload schema';
